In [1]:
import cv2
import numpy as np

In [22]:
# Reading the image in the console
image = cv2.imread("../../data/Lena.jpg")
# print(image)

# getting the height , width and depth of an image
height,width,color_channel= image.shape

In [23]:
# defining a zero pixeled image like the original image
image_after_operation = np.zeros_like(image,dtype=np.uint8)


# Manual looping for inverting an image
for y in range(height):
  for x in range(width):
    for z in range(color_channel):
      # do the operation here
      original_pixel_value = image[y,x,z]
      new_pixel_value = 255-original_pixel_value
      image_after_operation[y,x,z] = new_pixel_value 
      
print(image_after_operation)
cv2.imshow("Before inversion",image)
cv2.imshow("After inversion",image_after_operation)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[127 117  30]
  [128 118  31]
  [129 119  31]
  ...
  [129 110  19]
  [145 126  35]
  [169 151  58]]

 [[128 118  31]
  [128 118  31]
  [128 118  31]
  ...
  [125 105  20]
  [143 123  38]
  [172 153  66]]

 [[128 118  31]
  [128 118  31]
  [127 117  30]
  ...
  [128 107  25]
  [143 122  40]
  [170 150  65]]

 ...

 [[200 234 173]
  [201 235 174]
  [193 227 163]
  ...
  [173 184  80]
  [177 187  80]
  [181 190  80]]

 [[200 237 175]
  [199 236 174]
  [189 223 159]
  ...
  [173 186  78]
  [175 184  74]
  [174 183  72]]

 [[199 236 174]
  [197 234 172]
  [187 221 157]
  ...
  [174 187  79]
  [174 183  72]
  [171 181  67]]]
