In [ ]:
import cv2
import numpy as np


In [4]:
image = cv2.imread("../../data/Lena.jpg",cv2.IMREAD_GRAYSCALE)

# define the kernel
kernel = np.array([
    [0.075, 0.125, 0.075],
    [0.125, 0.200, 0.25],
    [0.075, 0.0025, 0.75]
])

anchor_row,anchor_col = 1,1

In [7]:
# Function for flipping the kernel manually
def flip_kernel(kernel):
  kernel_height,kernel_width = kernel.shape
  flipped_kernel = np.zeros((kernel_height,kernel_width),dtype=kernel.dtype)
  
  for i in range(kernel_height):
    for j in range(kernel_width):
      flipped_kernel[i,j] = kernel[kernel_height-1-i,kernel_width-1-j]
  
  return flipped_kernel

In [ ]:
# Function for convolution
def convolution(image,kernel,anchor_row,anchor_col):
  
  # Calculate the shape of image and kernel
  height,width = image.shape
  kernel_height,kernel_width = kernel.shape
  
  # Now we need to flip the kernel
  flipped_kernel = flip_kernel(kernel)
  
  # Padding calculation
  pad_top = anchor_row
  pad_bottom = kernel_height -anchor_row -1
  pad_left = anchor_col
  pad_right = kernel_width - anchor_col - 1
  
  padded_image = cv2.copyMakeBorder(image, pad_top, pad_bottom, pad_left, pad_right, cv2.BORDER_CONSTANT)
  
  
  #  Output image
  output_image = np.zeros((height, width), dtype=np.float64)
  
  
  # Do the convolution
  for v in range(height):
    for u in range(width):
      total = 0.0
      for j in range(kernel_height):
        for i in range(kernel_width):
          y = v + j
          x = u + i
          total = total + padded_image[y,x] * flipped_kernel[j,i]
      
      output_image[v,u] = int(round(total))
      
  output_image = np.round(output_image,None,0,255,cv2.NORM_MINMAX).astype(np.uint8)    
  return output_image

In [17]:
convolved_image = convolution(image = image, kernel = kernel, anchor_row = anchor_row, anchor_col = anchor_col)
print("Filtered image shape:", convolved_image)

cv2.imshow("Original Image", image)
cv2.imshow("Filtered Image", convolved_image)
cv2.waitKey(0)
cv2.destroyAllWindows()


Filtered image shape: [[ 46  82  81 ...  84  77  50]
 [ 54 173 172 ... 181 170 128]
 [ 54 172 172 ... 180 172 130]
 ...
 [  6  42  41 ... 103 105  83]
 [  5  39  40 ... 105 106  86]
 [  0  29  31 ...  86  87  74]]
