In [5]:
import cv2
import numpy as np

# # Reading the image
# image = cv2.imread("../../data/Lena.jpg", cv2.IMREAD_COLOR)
# if image is None:
#     print("Error: Could not load the image.")
#     exit()

# # Split the image into color channels
# blue, green, red = cv2.split(image)

# # Get sigma value from user
# sigma_value = input("Enter the sigma value for Gaussian filter: ")
# if sigma_value.isdigit():
#     sigma_value = float(sigma_value)  # Convert to float for GaussianBlur
# else:
#     print("Invalid input. Please enter a numeric value.")
#     exit()

# # Define kernel size (must be odd, choosing 5x5 as in your original code)
# kernel_size = 5

# # Apply GaussianBlur to each channel
# # sigmaX and sigmaY are the standard deviations in X and Y direction
# # If sigmaY is 0, it is set to sigmaX
# convolved_image_blue = cv2.GaussianBlur(blue, (kernel_size, kernel_size), sigmaX=sigma_value)
# convolved_image_green = cv2.GaussianBlur(green, (kernel_size, kernel_size), sigmaX=sigma_value)
# convolved_image_red = cv2.GaussianBlur(red, (kernel_size, kernel_size), sigmaX=sigma_value)

# # Merge the convolved channels back into a color image
# convolved_image = cv2.merge([convolved_image_blue, convolved_image_green, convolved_image_red])

# # Create colored images for individual channels (for visualization)
# height, width = convolved_image_blue.shape
# zeros = np.zeros((height, width), dtype=np.uint8)  # Zero array for empty channels
# blue_channel_colored = cv2.merge([convolved_image_blue, zeros, zeros])  # Blue channel (B, 0, 0)
# green_channel_colored = cv2.merge([zeros, convolved_image_green, zeros])  # Green channel (0, G, 0)
# red_channel_colored = cv2.merge([zeros, zeros, convolved_image_red])  # Red channel (0, 0, R)

# # Display each convolved channel as colored images
# cv2.imshow("Convolved Blue Channel", blue_channel_colored)
# cv2.imshow("Convolved Green Channel", green_channel_colored)
# cv2.imshow("Convolved Red Channel", red_channel_colored)

# # Display the merged convolved color image
# cv2.imshow("Convolved Color Image", convolved_image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [6]:
def create_gaussian_filter(sigma_value):
    print("Creating Gaussian filter with sigma value:", sigma_value)
    # Calculate kernel size based on sigma (common practice: 6*sigma + 1)
    kernel_size = int(6 * sigma_value + 1)
    if kernel_size % 2 == 0:  # Ensure odd kernel size
        kernel_size += 1
    
    return sigma_value, kernel_size

def Gaussian_Sharpening_Convolution(image, sigma_value, kernel_size):
    # Apply Gaussian blur
    blurred = cv2.GaussianBlur(image, (kernel_size, kernel_size), sigma_value)
    
    # Apply Laplacian filter
    laplacian = cv2.Laplacian(blurred, cv2.CV_64F)
    
    # Sharpen by subtracting the Laplacian from the original image
    # Sharpened = Original - Laplacian(Gaussian(Original))
    sharpened = image.astype(np.float64) - laplacian
    
    # Normalize to 0-255 range
    sharpened = np.clip(sharpened, 0, 255).astype(np.uint8)
    
    print("Sharpened image shape:", sharpened.shape)
    return sharpened

In [7]:
# Reading the image
image = cv2.imread("../../data/Lena.jpg", cv2.IMREAD_COLOR)
# Split the image
blue, green, red = cv2.split(image)

sigma_value = input("Enter the sigma value for Gaussian filter: ")
if sigma_value:
    sigma_value = float(sigma_value)
else:
    print("Invalid input. Please enter a numeric value.")
    sigma_value = None

if sigma_value is not None:
    sigma, kernel_size = create_gaussian_filter(sigma_value)
    
    # Apply sharpening to each channel using built-in functions
    convolved_image_blue = Gaussian_Sharpening_Convolution(blue, sigma, kernel_size)
    convolved_image_red = Gaussian_Sharpening_Convolution(red, sigma, kernel_size)
    convolved_image_green = Gaussian_Sharpening_Convolution(green, sigma, kernel_size)
    convolved_image = cv2.merge([convolved_image_blue, convolved_image_green, convolved_image_red])
    height, width = convolved_image_blue.shape
    zeros = np.zeros((height, width), dtype=np.uint8)  # Zero array for empty channels
    blue_channel_colored = cv2.merge([convolved_image_blue, zeros, zeros])  # Blue channel (B, 0, 0)
    green_channel_colored = cv2.merge([zeros, convolved_image_green, zeros])  # Green channel (0, G, 0)
    red_channel_colored = cv2.merge([zeros, zeros, convolved_image_red])  # Red channel (0, 0, R)
    
    # Display original color image
    cv2.imshow("Original Image", image)
    
    # Display each convolved channel as colored images
    cv2.imshow("Convolved Blue Channel", blue_channel_colored)
    cv2.imshow("Convolved Green Channel", green_channel_colored)
    cv2.imshow("Convolved Red Channel", red_channel_colored)
    
    print("Convolved image shape:", convolved_image)
    # Display the merged convolved color image
    
    cv2.imshow("Convolved Color Image", convolved_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
    # ...existing code for display...

Creating Gaussian filter with sigma value: 1.0
Sharpened image shape: (512, 512)
Sharpened image shape: (512, 512)
Sharpened image shape: (512, 512)
Convolved image shape: [[[128 138 225]
  [128 137 224]
  [123 137 224]
  ...
  [132 153 245]
  [105 121 218]
  [ 72  90 185]]

 [[127 136 224]
  [127 136 224]
  [130 138 224]
  ...
  [137 158 242]
  [107 129 212]
  [ 69  85 174]]

 [[128 138 223]
  [129 139 223]
  [128 137 225]
  ...
  [133 156 236]
  [110 132 214]
  [ 73  95 178]]

 ...

 [[ 51  15  76]
  [ 52  19  79]
  [ 63  28  91]
  ...
  [ 83  73 180]
  [ 79  67 179]
  [ 69  66 176]]

 [[ 53  13  75]
  [ 53  16  76]
  [ 68  36  98]
  ...
  [ 83  70 181]
  [ 78  72 186]
  [ 83  73 188]]

 [[ 52  15  75]
  [ 59  19  83]
  [ 72  36 103]
  ...
  [ 80  66 180]
  [ 82  75 186]
  [ 86  76 196]]]
