In [3]:
import cv2
import numpy as np



In [1]:
def log_transform(image):
    c = 255/np.log1p(np.max(image)) 
    image = c*(np.log1p(1+image))
    return image

In [4]:
original_image = cv2.imread("../../../data/Fig0305(a)(DFT_no_log).tif", cv2.IMREAD_GRAYSCALE)
cv2.imshow("Original Image", original_image)
log_transformed_image = log_transform(original_image)
log_transformed_image = np.clip(log_transformed_image, 0, 255).astype(np.uint8)
print(log_transformed_image)
cv2.imshow("Log Transformed Image", log_transformed_image) 

cv2.waitKey(0)
cv2.destroyAllWindows()

[[31 31 31 ... 31 31 31]
 [31 31 31 ... 31 31 31]
 [31 31 31 ... 31 31 31]
 ...
 [31 31 31 ... 31 31 31]
 [31 31 31 ... 31 31 31]
 [31 31 31 ... 31 31 31]]
