In [2]:
import cv2
import numpy as np

In [8]:
# first read the image
image = cv2.imread("../../data/Lena.jpg",cv2.IMREAD_GRAYSCALE)
# Now define the kernel
H = np.array([
    [0.075, 0.125, 0.075],
    [0.125, 0.200, 0.125],
    [0.075, 0.125, 0.075]
])
print("Image shape:", image.shape)

# Set the anchor here from the user or by the programmer
anchor_row,anchor_col = 1,1


Image shape: (512, 512)


In [12]:
def apply_filter(image, filter, anchor_row, anchor_col):
    height, width = image.shape
    kernel_height, kernel_width = filter.shape

    # Padding info
    pad_top = anchor_row
    pad_bottom = kernel_height - anchor_row - 1
    pad_left = anchor_col
    pad_right = kernel_width - anchor_col - 1

    # Create padded image
    padded_image = np.zeros((height + pad_top + pad_bottom,
                             width + pad_left + pad_right),
                            dtype=np.uint8)
    padded_image[pad_top:pad_top+height, pad_left:pad_left+width] = image

    # Output image
    output_image = np.zeros((height, width), dtype=np.uint8)

    # Apply filter
    for v in range(height):       # row
        for u in range(width):    # col
            total = 0.0
            for j in range(kernel_height):
                for i in range(kernel_width):
                    y = v + j
                    x = u + i
                    image_pixel = padded_image[y, x]
                    filter_pixel = filter[j, i]
                    total += image_pixel * filter_pixel
            output_image[v, u] = int(round(total))

    return output_image


In [14]:
filtered_image = apply_filter(image = image, filter = H, anchor_row = anchor_row, anchor_col = anchor_col)
print("Filtered image shape:", filtered_image)


# Show the original and filtered image
cv2.imshow("Original Image", image)
cv2.imshow("Filtered Image", filtered_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

Filtered image shape: [[ 85 117 117 ... 121 110  73]
 [118 162 162 ... 167 152 100]
 [118 162 162 ... 167 152 101]
 ...
 [ 32  46  48 ... 102 101  73]
 [ 31  46  50 ... 103 104  76]
 [ 22  34  37 ...  75  76  56]]
