In [22]:
import cv2
import numpy as np



In [23]:
  
def Gamma_Transform(image,gamma):
    img_float = image.astype(np.float32) / 255.0
    
    # apply gamma correction
    gamma_corrected = np.power(img_float, gamma)
    
    # rescale back to [0,255]
    gamma_corrected = np.uint8(gamma_corrected * 255)
    
    return gamma_corrected

In [24]:
original_image = cv2.imread("../../../data/Fig0308(a)(fractured_spine).tif", cv2.IMREAD_GRAYSCALE)
cv2.imshow("Original Image", original_image)

tansformed_image = Gamma_Transform(original_image, .3)
print(tansformed_image)
cv2.imshow("Gamma Transformed Image", tansformed_image)

cv2.waitKey(0)
cv2.destroyAllWindows()



[[ 0  0 48 ... 48 48 48]
 [ 0  0 48 ... 48 48 48]
 [ 0  0  0 ... 48  0  0]
 ...
 [48 48 48 ... 48 48 48]
 [48 48 48 ...  0  0  0]
 [48 48 48 ...  0  0  0]]
